### ISSUE TITLE
Issue when installing in Lua 5.3

### ISSUE THREAD

**Issue by kikito** [hoelzro/lua-term#16] opened 2016-04-03 23:16 UTC
Hi there,

I think the release which happened a couple hours ago might be making the installation of lua-term fail with Lua 5.3. I am getting this error:

```
gcc -O2 -fPIC -I/home/travis/build/kikito/i18n.lua/lua_install/include -c core.c -o core.o
In file included from /home/travis/build/kikito/i18n.lua/lua_install/include/lua.h:16:0,
                 from core.c:3:
/home/travis/build/kikito/i18n.lua/lua_install/include/luaconf.h:567:2: error: #error "Compiler does not support 'long long'. Use option '-DLUA_32BITS'   or '-DLUA_C89_NUMBERS' (see file 'luaconf.h' for details)"
In file included from core.c:3:0:
/home/travis/build/kikito/i18n.lua/lua_install/include/lua.h:93:1: error: unknown type name ‘LUA_INTEGER’
/home/travis/build/kikito/i18n.lua/lua_install/include/lua.h:96:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘lua_Unsigned’
Error: Failed installing dependency: https://luarocks.org/lua-term-0.5-1.rockspec - Build error: Failed compiling object core.o
```

Example in travis: https://travis-ci.org/kikito/i18n.lua/jobs/120504745#L191

**Comment by hoelzro** [comment] 2016-04-03 23:39
@kikito I don't use Lua 5.3; any suggestions for a fix?  I don't want to force compiler flags like `-DLUA_C89_NUMBERS` on users if I don't have to.

**Comment by tst2005** [comment] 2016-04-04 08:48
If you are not so strict...
I made a fallback in case of `term.core` not available, see [term.corefallback](https://github.com/tst2005/lua-term/blob/core-fallback/term/corefallback.lua).
It just fake the term is a tty.

Regards,

**Comment by mpeterv** [comment] 2016-04-04 11:08
The problem is that with _POSIX_SOURCE defined features.h doesn't define __USE_ISOC99, which in turn means that LLONG_MAX isn't defined, which in turns makes luaconf.h think that `long long` type is not available. Removing _POSIX_SOURCE from core.c fixes the issue and doesn't result in any compiler warnings at least for me (I use gcc 4.8.4).

**Comment by hoelzro** [comment] 2016-04-04 13:17
@mpeterv Thanks for the tip; however, I still get the error about `Compiler does not support 'long long'`, and I also get a warning about an implicit declaration of `fileno`, which is why I added the `_POSIX_SOURCE` define in the first place.  I'm on gcc 5.3.0; maybe that has something to do with it?

**Comment by hoelzro** [comment] 2016-04-04 13:17
@tst2005 If you have an feature you would like to have added or code you would like incorporated, please file a separate issue or pull request.

**Comment by mpeterv** [comment] 2016-04-04 16:37
@hoelzro interesting, so luarocks is broken for combination of Lua 5.3 and gcc 5? Unfortunately I can't easily test this. Does it produce an error if you manually compile with -std=gnu99?

**Comment by blueyed** [comment] 2016-04-04 18:46
@mpeterv 
A build log would be available on https://travis-ci.org/awesomeWM/awesome/jobs/120692700 (it uses gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4).

**Comment by hoelzro** [comment] 2016-04-05 00:55
Alright, I figured out the culprit: the `-ansi` flag.  I've removed it and made a new release.

**Comment by mpeterv** [comment] 2016-04-05 09:23
But `-ansi` flag is in the makefile while the rockspec uses builtin back-end, so nothing changed. FTR Luarocks builds core.o using this command: `gcc -O2 -fPIC -I/home/mpeterv/lua53/include -c core.c -o core.o`

**Comment by hoelzro** [comment] 2016-04-05 12:52
@mpeterv Are you still having issues?  I tested with both `make` and a `luarocks build`.

**Comment by kikito** [comment] 2016-04-05 13:45
I confirm that I am still seeing the same issue. Re-run https://travis-ci.org/kikito/i18n.lua/jobs/120504745 and obtained the same error.

**Comment by hoelzro** [comment] 2016-04-05 13:50
Ah, it must have something to do with GCC and the default C standard.  GCC 5.3.0 (I assume) defaults to C99; anyone know what version of GCC travis has?

**Comment by hoelzro** [comment] 2016-04-05 14:34
It seems that it's 4.6.3:

https://travis-ci.org/hoelzro/lua-term/builds/120903685

**Comment by kikito** [comment] 2016-04-05 14:36
You can see it by "opening" the section called "Build System Information", near the top of the log. It says

> gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

On my travis pr (I use the default).

**Comment by hoelzro** [comment] 2016-04-05 15:42
Alright, I have the `CFLAGS` fixed in the Makefile, but I can't seem to figure out how to modify the flags passed to the compiler when a `luarocks build` is done.  Any ideas?

**Comment by kikito** [comment] 2016-04-05 16:01
My C knowledge is limited so my suggestions will probably be dumb; but here they are: First, it seems that if you want to use `_POSIX_SOURCE` with Lua 5.3 you need to do something on top of that. Maybe you need to define `__USE_ISOC99` too? Or maybe `LLONG_MAX`?

Or, you could remove the `_POSIX_SOURCE` part. Maybe there is a way to make the warning about `fileno` go away without using `_POSIX_SOURCE`. Even if there isn't, trading a warning for an error seems reasonable.

**Comment by hoelzro** [comment] 2016-04-05 16:18
I don't really understand why `_POSIX_SOURCE` causes an error , but you're right; a warning is better than an error.  I'll push out a new release after work.

**Comment by mpeterv** [comment] 2016-04-05 17:06
> Maybe there is a way to make the warning about fileno go away without using _POSIX_SOURCE.

`man fileno` says that macro requirements can be expressed as `_POSIX_C_SOURCE >= 1 || _XOPEN_SOURCE || _POSIX_SOURCE`.  `#define _POSIX_C_SOURCE 200112L` worked for me.

**Comment by hoelzro** [comment] 2016-04-05 17:13
@mpeterv Thanks for the input!  I learned something new today =)

**Comment by mpeterv** [comment] 2016-04-05 17:37
@hoelzro no problem, looking forward for a new release!

**Comment by hoelzro** [comment] 2016-04-06 03:13
Ok, 0.07 is out now; let me know if there are any further problems!

**Closed by hoelzro** 2016-04-06 03:13 UTC

**Comment by psychon** [comment] 2016-04-06 08:15
I can confirm that 0.07 works for me on Travis where 0.06 and 0.05 failed (all tried without any modifications on my side, I just made Travis restart the build).

**Comment by kikito** [comment] 2016-04-12 07:17
I also confirm the green status. Thanks a lot, everyone!
